### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by smonjezi1** [juliomalegria/python-craigslist#61] opened 2019-01-13 20:58 UTC
Thank you for making this awesome package. I tried to run your example and it returns with an error after a few  seconds.

code:

    from craigslist import CraigslistHousing
    cl_h = CraigslistHousing(site='sfbay', area='sfc', category='roo',
                             filters={'max_price': 1200, 'private_room': True})
    for result in cl_h.get_results(sort_by='newest', geotagged=True):
        print result

Output:

Traceback (most recent call last):
  File "/get_data_test.py", line 35, in <module>
    print (result)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 56-56: Non-BMP character not supported in Tk

**Comment by Rafalonso** [comment] 2019-08-09 08:56
What's your python version?

**Comment by juliomalegria** [comment] 2019-08-27 10:40
I can't reproduce this. Please reopen the issue if you're still seeing this, sharing a bit more info (Python version would be nice). I'm closing this since it's quite old.

**Closed by juliomalegria** 2019-08-27 10:40 UTC
